version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: rails_development
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mail
      - address
