version: "3.7"
services:
  db:
    image: postgres:10
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "54320:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: rails_production
    env_file:
      - .env
    ports:
      - "3000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
      args:
        SERVER_NAME: ${NGINX_SERVER_NAME}
    depends_on:
      - app
    ports:
      - 80:80
  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
volumes:
  db_volume:
