version: '3'
services:
  db:
    image: postgres:10
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "54320:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/myapp
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
