version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: rails_test
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./env/.env.test
    depends_on:
      - db
      - mail
      - address
