version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: rails_development
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./env/.env.development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mail
      - address
