version: "3.7"
services:
  db:
    image: postgres:10
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "54320:5432"
  app:
    build:
      context: .
      dockerfile: production.Dockerfile
    volumes:
      - app_volume:/usr/src/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        SERVER_NAME: ${NGINX_SERVER_NAME}
    volumes:
      - app_volume:/usr/src/app
    depends_on:
      - app
    ports:
      - 80:80
volumes:
  db_volume:
  app_volume:
