version: "3.7"

services:
  db:
    image: postgres:10
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "54320:5432"
  mail:
    image: schickling/mailcatcher
    expose:
      - "1025"
    ports:
      - 1080:1080
  address:
    build:
      context: .
      dockerfile: Dockerfile
      target: address
    environment:
      - OS_PLACES_KEY
    ports:
      - "9002:9002"
      - "9003:9003"

volumes:
  db_volume:
